# 使用说明 V6.0 - 单体架构版本
# 1. 先构建单体 JAR: mvn clean install -Pboot -DskipTests
# 2. 启动服务: docker compose -f docker-compose-boot.yml up -d
# 3. 静静等待服务启动
services:
  pigx-mysql:
    build:
      context: ./db
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
    restart: always
    container_name: pigx-mysql
    image: pigx-mysql
    command: --lower_case_table_names=1
    networks:
      - spring_cloud_default

  pigx-redis:
    container_name: pigx-redis
    image: registry.cn-hangzhou.aliyuncs.com/dockerhub_mirror/redis
    restart: always
    networks:
      - spring_cloud_default

  # 单体的时候注意，服务名称命名为 pigx-gateway 对应前端nginx 配置
  pigx-gateway:
    build:
      context: ./pigx-boot
    restart: always
    container_name: pigx-boot
    image: pigx-boot
    ports:
      - 9999:9999
    networks:
      - spring_cloud_default

networks:
  spring_cloud_default:
    name: spring_cloud_default
    driver: bridge
