export const tableOption = {
  "border": true,
  "index": true,
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "editBtn": false,
  "delBtn": false,
  "dic": [],
  "column": [{
    width: 150,
    "label": "client_id",
    "prop": "clientId",
    align: 'center',
    sortable: true,
    rules: [{
      required: true,
      message: "请输入clientId",
      trigger: "blur"
    }]
  }, {
    width: 300,
    "label": "client_secret",
    "prop": "clientSecret",
    align: 'center',
    sortable: true,
    rules: [{
      required: true,
      message: "请输入clientSecret",
      trigger: "blur"
    }]
  }, {
    "label": "resource_ids",
    "prop": "resourceIds",
    align: 'center',
    width: 150,
  }, {
    "label": "scope",
    "prop": "scope",
    align: 'center',
    width: 150,
    rules: [{
      required: true,
      message: "请输入scope",
      trigger: "blur"
    }]
  }, {
    "label": "authorized_grant_types",
    "prop": "authorizedGrantTypes",
    align: 'center',
    width: 150,
    hide: true,
  }, {
    "label": "web_server_redirect_uri",
    "prop": "webServerRedirectUri",
    align: 'center',
    width: 150,
    hide: true,
  }, {
    "label": "authorities",
    "prop": "authorities",
    align: 'center',
    width: 150,
    hide: true,
  }, {
    "label": "access_token_validity",
    "prop": "accessTokenValidity",
    align: 'center',
    width: 150,
    hide: true,
  }, {
    "label": "refresh_token_validity",
    "prop": "refreshTokenValidity",
    type: 'number',
    align: 'center',
    width: 150,
    hide: true,
  }, {
    "label": "additional_information",
    "prop": "additionalInformation",
    type: 'number',
    align: 'center',
    width: 150,
    hide: true,
  }, {
    "label": "autoapprove",
    "prop": "autoapprove",
    align: 'center',
    type: 'radio',
    dicData: [{
      label: '假',
      value: 'false',
    }, {
      label: '真',
      value: 'true',
    }],
    width: 150,
  }]
}
