server:
  port: 9999
  servlet:
    context-path: /admin
  undertow:
    max-http-post-size: 100MB

spring:
  application:
    name: @project.artifactId@
  # 缓存相关配置
  cache:
    type: redis
  # 上传文件大小限制
  servlet:
    multipart:
      max-file-size: ${server.undertow.max-http-post-size}
      max-request-size: ${server.undertow.max-http-post-size}
  cloud:
    discovery:
      enabled: false
    nacos:
      config.enabled: false
      discovery.enabled: false
    gateway:
      server.webflux:
        enabled: false
        redis.enabled: false
    sentinel.enabled: false
    openfeign.okhttp.enabled: true
  freemarker: # freemarker 配置，授权码模式页面渲染使用
    suffix: .ftl
    template-loader-path: classpath:/templates/
    request-context-attribute: request
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev


## spring security 对外暴露接口设置
security:
  micro: false
  oauth2:
    client:
      ignore-urls:
        - /webjars/**
        - /v3/api-docs/**
        - /doc.html
        - /swagger-ui.html
        - /swagger-ui/**
        - /swagger-resources
        - /token/**
        - /error
        - /druid/**
        - /actuator/**
        - /code/**

#--------------如下配置尽量不要变动-------------
management.endpoints.access.default: none # 默认所有端点都不允许访问
# mybatis-plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      where-strategy: not_empty
      insert-strategy: not_empty
      update-strategy: not_null
  type-handlers-package: com.pig4cloud.pig.common.data.handler
  configuration:
    jdbc-type-for-null: 'null'
    call-setters-on-nulls: true
    shrink-whitespaces-in-sql: true